export const S = {
  root: (bg) => ({ minHeight:"100dvh", background:bg||"#080808", display:"flex", justifyContent:"center", color:"#fff", fontFamily:"'Trebuchet MS','Tahoma',sans-serif", overflowX:"hidden" }),
  page: { width:"100%", maxWidth:420, padding:"28px 20px 70px", display:"flex", flexDirection:"column", gap:14 },
  topNav: { display:"flex", justifyContent:"space-between", alignItems:"center" },
  rankPill: (c) => ({ display:"flex", alignItems:"center", gap:6, background:c+"18", border:`1px solid ${c}44`, borderRadius:999, padding:"4px 14px", fontSize:12, letterSpacing:1, color:c }),
  heroTitle: { fontSize:48, fontWeight:900, margin:0, lineHeight:1.05, letterSpacing:-2, textAlign:"center", textShadow:"0 0 40px #fff1" },
  card: (c) => ({ background:"#ffffff07", border:`1px solid ${c}22`, borderRadius:18, padding:"16px" }),
  row: { display:"flex", justifyContent:"space-between", alignItems:"center" },
  warn: { background:"#f8717118", border:"1px solid #f8717144", borderRadius:12, padding:"10px 14px", color:"#f87171", fontSize:13 },
  grid4: { display:"grid", gridTemplateColumns:"1fr 1fr 1fr 1fr", gap:8 },
  grid3: { display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:8 },
  grid2: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 },
  playBtn: (c) => ({ width:"100%", padding:"18px", background:`linear-gradient(135deg,${c}cc,${c})`, border:"none", borderRadius:18, color:"#000", fontWeight:900, fontSize:20, letterSpacing:3, cursor:"pointer", boxShadow:`0 6px 28px ${c}44` }),
  dailyRow: (d) => ({ display:"flex", justifyContent:"space-between", alignItems:"center", background:d?"#4ade8010":"#ffffff08", border:`1px solid ${d?"#4ade8033":"#ffffff11"}`, borderRadius:12, padding:"12px 16px", fontSize:14 }),
  backBtn: { background:"none", border:"none", color:"#555", fontSize:15, cursor:"pointer", padding:0 },
  title: (c) => ({ fontSize:28, fontWeight:900, margin:0, letterSpacing:-1, color:c }),
  modeCard: (c, l) => ({ background:l?"#ffffff05":"#ffffff0a", border:`1px solid ${l?"#222":c+"33"}`, borderRadius:18, padding:"20px 12px", cursor:l?"default":"pointer", color:l?"#444":"#fff", textAlign:"center", opacity:l?0.6:1 }),
  badge: { display:"inline-block", border:"1px solid", borderRadius:999, padding:"3px 12px", fontSize:11, fontWeight:700 },
  qCard: (fb, c) => ({ background:fb==="correct"?"#22c55e18":fb==="wrong"?"#ef444418":"#ffffff09", border:`2px solid ${fb==="correct"?"#22c55e":fb==="wrong"?"#ef4444":c+"33"}`, borderRadius:24, padding:"36px 24px", textAlign:"center", transition:"all 0.2s" }),
  qMain: { fontSize:52, fontWeight:900, letterSpacing:-2, lineHeight:1 },
  choice: (s, c) => ({ padding:"22px 8px", borderRadius:18, border:`2px solid ${s==="correct"?"#22c55e":s==="hint"?"#22c55e55":s==="dim"?"#ffffff0a":c+"44"}`, background:s==="correct"?"#22c55e22":s==="hint"?"#22c55e11":s==="dim"?"#ffffff05":"#ffffff0a", color:s==="dim"?"#333":"#fff", fontSize:28, fontWeight:900, cursor:"pointer", transition:"all 0.12s", WebkitTapHighlightColor:"transparent" }),
  stopBtn: { marginTop:4, padding:"11px 0", width:"100%", background:"none", border:"1px solid #2a2a2a", borderRadius:12, color:"#555", fontSize:13, cursor:"pointer" },
  promo: (c) => ({ display:"flex", gap:12, alignItems:"center", background:c+"18", border:`1px solid ${c}44`, borderRadius:16, padding:"14px 16px" }),
  homeBtn: { flex:1, padding:"15px", background:"#ffffff0a", border:"1px solid #2a2a2a", borderRadius:14, color:"#777", fontWeight:700, fontSize:15, cursor:"pointer" },
  sTitle: { fontSize:11, color:"#555", textTransform:"uppercase", letterSpacing:1.5, marginBottom:12 },
  toggle: (on, c) => ({ padding:"5px 12px", borderRadius:999, background:on?c+"33":"#ffffff0a", border:`1px solid ${on?c+"66":"#333"}`, color:on?c:"#555", fontWeight:800, fontSize:11, letterSpacing:1, cursor:"pointer" }),
};
