export const TIERS = [
  { id:"beginner", label:"Beginner", emoji:"🟢", rank:0, color:"#4ade80", bg:"#020f06",
    xpMin:0, xpMax:500, requiredAccuracy:0, minQuestions:0, hints:true, timeLimit:null,
    desc:"Leer de basis. Geen tijdsdruk." },
  { id:"amateur", label:"Amateur", emoji:"🔵", rank:1, color:"#60a5fa", bg:"#020810",
    xpMin:500, xpMax:1500, requiredAccuracy:70, minQuestions:30, hints:false, timeLimit:8,
    desc:"Lichte tijdsdruk. Combo actief." },
  { id:"advanced", label:"Gevorderd", emoji:"🟣", rank:2, color:"#c084fc", bg:"#08020f",
    xpMin:1500, xpMax:3500, requiredAccuracy:78, minQuestions:80, hints:false, timeLimit:6,
    desc:"Procenten ontgrendeld. Mix van alles." },
  { id:"pro", label:"Pro", emoji:"🔴", rank:3, color:"#f87171", bg:"#0f0202",
    xpMin:3500, xpMax:7000, requiredAccuracy:85, minQuestions:200, hints:false, timeLimit:5,
    desc:"Strikte tijdslimiet. Survival mode." },
  { id:"elite", label:"Elite", emoji:"⭐", rank:4, color:"#fbbf24", bg:"#0f0a00",
    xpMin:7000, xpMax:99999, requiredAccuracy:92, minQuestions:500, hints:false, timeLimit:3,
    desc:"Extreem snel. Adaptive AI. Geen hints." },
];
